### ISSUE TITLE
Use SANs and wildcards to reduce number of certificates generated

### ISSUE THREAD

**Issue by vcsjones** [vcsjones/FiddlerCertGen#1]
The number of certificates that need to be generated can be reduced by using subject alternative names. This is especially useful for some services, like AWS CloudFront and other edge cache providers. Consider the URL:

```
https://abc132.cloudfront.net
https://def465.cloudfront.net
```

It would be easier to generate a certificate for `*.cloudfront.net` and `cloudfront.net`.

Wildcards do not support nesting, i.e. `*.a.com` is not valid for `w.b.a.com`, and certificates cannot contain multiple wildcards like `*.*.*.a.com`.

A new certificate would have to be generated for each level of a subdomain.

**Comment by vcsjones** [comment]
This will help with the number of certificates that we need to keep in-memory and alleviate memory pressure.

**Comment by ericlaw1979** [comment]
Genius idea. 4.6.0.8 gets this for the default cert generators, gated behind the preference FiddlerApplication.Prefs.GetBoolPref("fiddler.certmaker.UseWildcards", true);

There's one subtlety here, in that CertMakers offer a `StoreCert` method that allows a developer to pre-cache a cert (typically used when they have a CA-issued cert they want to use with Fiddler to avoid problems with pinning in a mobile app). If a dev calls that method, then your code that checks a memory cache needs to be smart enough to look for the specific host first, then look for a wildcard. For now, I'm just punting on that and if you call StoreCert you should disable the wildcard preference.

**Comment by ericlaw1979** [comment]
I'm not sure how current this list is: https://www.digicert.com/ssl-support/wildcard-compatibility.htm but it's a bit worrisome.

**Comment by vcsjones** [comment]
Great, I'll get around to adding this to my generator eventually, I'll respect that preference as well.

**Comment by vcsjones** [comment]
@EricLaw I would be really interested to know how you implemented this! For example, if I visit `poo.co.uk` do you generate a wildcard for `co.uk`, or is there some smarts to detect "multi-level" TLDs?

**Comment by vcsjones** [comment]
OK, here is my approach I will take. Please shoot holes in it.

If the domain is two letters (like `co`) then _don't_ treat it as a subdomain. So:
- `abc.co.uk` - has no subdomain because all components up-to the TLD are < 3 letters.
- `abc.co.er.uk` - has no subdomain because all components up-to the TLD are < 3 letters.
- `abc.corn.uk` - `abc` is the subdomain
- `abc.uk` - has no subdomain

**Comment by ericlaw1979** [comment]
I'm conservative.

`arrWildcardableTLDs = new[] { ".com", ".org", ".edu", ".gov", ".net" };`

The Public Suffix List (publicsuffix.org) quickly goes off into crazy-pants land after that, and the "traditional" TLDs cover a huge percentage of the cases we care about.

**Comment by vcsjones** [comment]
I went in guns blazing.
